workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ios.nequixofficialv2
      
      vars:
        XCODE_WORKSPACE: "iosApp/NequixiOS.xcworkspace"
        XCODE_SCHEME: "NequixiOS"
        XCODE_PROJECT: "iosApp/NequixiOS.xcodeproj"
        
      xcode: 15.0
      cocoapods: default
      groups:
        - codemagic
        
    scripts:
      - name: Prepare iOS Build
        script: |
          chmod +x ./gradlew
          chmod +x ./prepare_ios_build.sh || true
          
      - name: Build Shared Framework
        script: |
          ./gradlew :shared:podInstall
          
      - name: Install CocoaPods Dependencies
        script: |
          cd iosApp
          pod install --repo-update
          
      - name: Set up code signing
        script: |
          keychain initialize
          
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
            
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - tu-email@gmail.com
        notify:
          success: true
          failure: true
