#!/bin/bash

IPA_PATH="build/NequixiOS.ipa"

if [ ! -f "$IPA_PATH" ]; then
    echo "Error: No se encontro el archivo IPA en $IPA_PATH"
    echo "Ejecuta primero: ./build_ipa.sh"
    exit 1
fi

IPA_ABS=$(realpath "$IPA_PATH")
IPA_SIZE=$(du -h "$IPA_PATH" | cut -f1)

echo "═══════════════════════════════════════════════════════════════"
echo "  📱 OPCIONES PARA PROBAR IPA EN EMULADOR ONLINE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📦 Archivo IPA: $IPA_ABS"
echo "📊 Tamaño: $IPA_SIZE"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  OPCION 1: Appetize.io (Recomendado)"
echo "═══════════════════════════════════════════════════════════════"
echo "1. Ve a: https://appetize.io/"
echo "2. Crea una cuenta gratuita (tiene limite de minutos)"
echo "3. Sube tu archivo IPA: $IPA_ABS"
echo "4. Selecciona el modelo de iPhone (iPhone 14, 15, etc.)"
echo "5. Selecciona la version de iOS"
echo "6. Click en 'Start' para iniciar el emulador"
echo ""
echo "💡 Ventajas:"
echo "   - Gratis con limites"
echo "   - No requiere instalacion"
echo "   - Funciona desde el navegador"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  OPCION 2: TestingBot"
echo "═══════════════════════════════════════════════════════════════"
echo "1. Ve a: https://testingbot.com/"
echo "2. Crea una cuenta"
echo "3. Sube tu IPA en la seccion de pruebas"
echo "4. Selecciona dispositivo iOS real"
echo "5. Inicia la prueba remota"
echo ""
echo "💡 Ventajas:"
echo "   - Dispositivos reales"
echo "   - Mas preciso que emuladores"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  OPCION 3: BrowserStack"
echo "═══════════════════════════════════════════════════════════════"
echo "1. Ve a: https://www.browserstack.com/app-live"
echo "2. Crea cuenta (tiene periodo de prueba)"
echo "3. Sube tu IPA"
echo "4. Prueba en diferentes dispositivos iOS"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  OPCION 4: LambdaTest"
echo "═══════════════════════════════════════════════════════════════"
echo "1. Ve a: https://www.lambdatest.com/mobile-app-testing"
echo "2. Registrate"
echo "3. Sube tu IPA"
echo "4. Prueba en emuladores iOS"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  IMPORTANTE: Limitaciones"
echo "═══════════════════════════════════════════════════════════════"
echo "⚠️  Este IPA es una estructura basica creada desde Linux"
echo "⚠️  Para que funcione completamente necesitas:"
echo "   1. Compilar el codigo Swift (requiere macOS/Xcode)"
echo "   2. Framework compartido compilado para iOS"
echo "   3. Firma con certificado de desarrollador"
echo ""
echo "⚠️  El IPA actual puede no ejecutarse completamente"
echo "    porque falta el binario Swift compilado"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  ACCESO RAPIDO AL ARCHIVO"
echo "═══════════════════════════════════════════════════════════════"
echo "Ruta completa:"
echo "$IPA_ABS"
echo ""
echo "Para copiar la ruta:"
echo "echo '$IPA_ABS' | xclip -selection clipboard"
echo ""

