# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'NequixiOS' do
  use_frameworks!

  pod 'shared', :path => '../shared'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
    
    # Fix para nanopb-nanopb_Privacy bundle error - deshabilitar CopySwiftLibs
    if target.name == 'nanopb-nanopb_Privacy'
      target.build_phases.each do |phase|
        if phase.respond_to?(:name) && phase.name == 'CopySwiftLibs'
          target.build_phases.delete(phase)
        end
      end
    end
  end
end
